name: Build Docker Image


on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - name: Descargar código
        uses: actions/checkout@v4

      - name: Login a GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir imagen Docker
        run: |
          docker build -t ghcr.io/mezitajr-ship-it/mi-app:${{ github.sha }} .

      - name: Publicar imagen en GHCR
        run: |
          docker push ghcr.io/mezitajr-ship-it/mi-app:${{ github.sha }}     
